FROM openjdk:17-slim
WORKDIR /app

# Copy the control-producer jar
COPY target/control-producer-app-jar-with-dependencies.jar /app/control-app.jar

ENTRYPOINT ["java", "-jar", "/app/control-app.jar"]
